devices:
  names:
    #- UD24_BLE
    #- DT24TW_BLE
    #- DL24M_BLE
    #- AT24_BLE
    #- xiaoxiang BMS
    - FNB48s-021356
  services: []
    #- '0000ffe0-0000-1000-8000-00805f9b34fb' # ATorch service
    #- '0000ff00-0000-1000-8000-00805f9b34fb' #XiaoXiang service
storage:
  type: console
  influxdb:
    bucket: ble-meters
    url: http://localhost:8086
    org: org
    token: Qg3cCxFyUmLtDIqcEC26oMn0QkhymbDyAvXfT4YrH5Qz-cKi_0sO_8c4Bdl5by2tk0gztDibcBZ192ZNJCqr_g==
  csv:
    path: '.'
    is_gzip: false
  console:
    type: pretty
logging:
  warning:
    - storage
    #- scanner
    #- client
  debug:
    - scanner
    - client
    - fnirsi
    #- atorch
    #- xiaoxiang

