#devices:
#  names:
#    - UD24_BLE
#    - DT24TW_BLE
#  services
#    - '0000ffe0-0000-1000-8000-00805f9b34fb' # ATorch service
debug:
  - scanner
  - client
  - protocols
  - storage
storage:
  type: console
  influxdb:
    bucket: usb-meters
    url: http://localhost:8086
    org: drovalev
    token: 3SMiB5ksX8rCB2zJE19hkz0goeav-pZiWMBJcft1k5PsWGB7DyxPv1r8qK-PwDxcZSfNP16XlT22ldCkd8kurg==
  csv:
    path: '.'
    is_gzip: false
  console:
    type: pretty

