devices:
  atorch:
    - UD24_BLE
    - DT24TW_BLE
    - DL24M_BLE
    - AT24_BLE
  xiaoxiang:
    - xiaoxiang BMS
  fnirsi:
    - FNB48s-021356
storage:
  type: console
  influxdb:
    bucket: ble-meters
    url: http://localhost:8086
    org: org
    token: Qg3cCxFyUmLtDIqcEC26oMn0QkhymbDyAvXfT4YrH5Qz-cKi_0sO_8c4Bdl5by2tk0gztDibcBZ192ZNJCqr_g==
  csv:
    path: '.'
    is_gzip: false
  console:
    type: pretty
logging:
  warning:
    - storage
    #- scanner
    #- client
  debug:
    - scanner
    - client
    - fnirsi
    #- atorch
    #- xiaoxiang

