storage:
  type: influxdb
  influxdb:
    bucket: ble-meters
    url: http://localhost:8086
    org: org
    token: Qg3cCxFyUmLtDIqcEC26oMn0QkhymbDyAvXfT4YrH5Qz-cKi_0sO_8c4Bdl5by2tk0gztDibcBZ192ZNJCqr_g==
  influxdb-dev:
    bucket: usb-meters
    url: http://localhost:8086
    org: drovalev
    token: 3SMiB5ksX8rCB2zJE19hkz0goeav-pZiWMBJcft1k5PsWGB7DyxPv1r8qK-PwDxcZSfNP16XlT22ldCkd8kurg==
  csv:
    path: '.'
    is_gzip: false
  console:
    type: pretty
logging:
  error:
    - proto
    - storage
